name: Evaluate Dataset

on:
  push:
    paths:
      - 'data/**'
      - 'scripts/**'
  pull_request:
    paths:
      - 'data/**'
      - 'scripts/**'

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Python dependencies
        run: |
          pip install pandas scikit-learn

      - name: 🧪 Run basic dataset evaluation
        run: python scripts/evaluate.py

      - name: 🔍 Run prediction evaluation (if column exists)
        run: python scripts/evaluate_with_predictions.py
